config/routes.rb
Urbo::Application.routes.draw do
  root :to => 'browse#index'
  match ':year/:month' => 'browse#month', :year => /\d+/, :month => /\d+/, :as => :period
  match ':year/:month/:day.:format' => 'browse#download', :year => /\d+/, :month => /\d+/, :day => /\d+/
  get "search", :controller => 'search', :action => 'index'

  delete 'logout' => 'sessions#destroy', :as => 'destroy_admin_session'
  get 'login' => 'sessions#new'
  resources :sessions

  resources :subscriptions
end

app/views/admin/templates/_date.html.erb
<li id="<%= attribute_id %>">
  <%= form.label attribute, label_text %>
  <%= form.text_field attribute, value: @item.send(attribute) && l(@item.send(attribute)), class: 'datepicker' %>
</li>

app/views/admin/templates/_generate_pdf.html.erb
<% unless params[:publish] %>
<li id="<%= attribute_id %>">
  <%= form.label attribute, _('Gerar PDF') %>
  <%= form.hidden_field attribute, value: true %>
  <table style='border: 1px solid #babdb6;'>
    <tr>
      <th><%= _('Gerar um novo arquivo') %></th>
      <th><%= _('Arquivo existente') %></th>
    </tr>
    <tr>
      <td>
        <p><%= _('Ao clicar em "Salvar", será gerado o diário oficial com os seguintes assuntos:') %></p>
        <ul class='text'>
        <% if @item.official_diary.present? %>
          <% books = @item.official_diary.subjects.group_by(&:book) %>
          <% books.keys.sort_by(&:created_at).sort_by(&:position).each do |book| %>
            <% subjects = books[book].sort_by(&:created_at).sort_by(&:position) %>
            <li>
              <%= book.name %>
              <ul>
                <% subjects.each do |subject| %>
                  <li><%= subject.title %></li>
                <% end %>
              </ul>
            </li>
          <% end %>
        <% end %>
      </ul>
      </td>
      <td>
        <% if @item.data.present? && @item.official_diary.present? %>
          <%= link_to _('Download'), download_path(@item.official_diary) %>
        <% else %>
          <em><%= _('(Nenhum)') %></em>
        <% end %>
      </td>
    </tr>
  </table>
</li>
<% end %>

app/views/admin/templates/_manage_pdf.html.erb
<% return '' unless @item.persisted? %>

<div style='margin: 30px 0px 30px 0px'>
  <h2>
    <%= _('PDF') %>
    <% if Rails.env.development? %>
      <small>
        (<%= link_to _('LaTeX source'), action: 'source', id: @item.id %>)
      </small>
    <% end %>
  </h2>


  <% if @item.attachment.present? %>
    <table style='vertical-align: bottom'>
      <tr>
        <td style='vertical-align: bottom'>
          <% download_url = download_path(@item) + '?t' + Time.now.to_i.to_s %>
          <%= link_to(download_url, target: '_blank') do %>
            <%= image_tag 'pdfreaders-f-22px.png', style: 'vertical-align: bottom' %>
            <%= _('Download') -%>
          <% end %>
        </td>
        <td style='vertical-align: bottom'>
          <%= link_to _('Atualizar'), { controller: 'admin/attachments', action: 'edit', id: @item.attachment.id, _popup: true }, class: 'iframe_with_page_reload' %>
        </td>
        <td style='vertical-align: bottom'>
          <%= link_to _('Remover'), { controller: 'admin/attachments', action: 'destroy', id: @item.attachment.id }, method: :delete, confirm: _('Tem certeza que quer remover?') %>
        </td>
      </tr>
      <tr>
        <td colspan='3' style='padding-top: 20px'>
          <%= content_tag :button, href: url_for(controller: 'admin/attachments', action: 'edit', id: @item.attachment.id, _popup: true, publish: true), class: 'iframe_with_page_reload' do %>
            <%= _('Publicar') %>
          <% end %>
        </td>
      </tr>
    </table>
  <% else %>
    <% if @item.subjects.empty? %>
      <p><em><%= _('É necessário adicionar assuntos antes de gerar um PDF') %></em></p>
    <% else %>
      <%= content_tag :button, href: url_for(controller: 'admin/attachments', action: 'new', _popup: true, resource: { official_diary_id: @item.id }), class: 'iframe_with_page_reload' do %>
        <%= _('Gerar PDF') %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/admin/templates/_publish.html.erb
<% if params[:publish] %>
  <%= form.hidden_field attribute, value: true %>
  <%= hidden_field_tag :publish, true %>
<% end %>

app/views/admin/templates/_subjects.html.erb
<% return '' unless @item.persisted? %>

<h2><%= _('Assuntos') %></h2>

<% if @item.published? %>
  <div class='published-warning'>
    <strong><%= _('Atenção.') %></strong>
    <%= _('Este diário oficial já foi publicado') %>
  </div>
<% end %>

<div style='margin-bottom: 1em'>
  <button class='iframe_with_page_reload' href='<%= url_for controller: 'admin/subjects', action: 'new', _popup: true, resource: { official_diary_id: @item.id } %>'><%= _('Adicionar assunto') %></button>
</div>

<% books = @item.subjects.group_by(&:book) %>
<table>
<% books.keys.sort_by(&:created_at).sort_by(&:position).each do |book| %>
  <tr>
    <td colspan='4' style='background: #eeeee5; border-bottom: 1px solid #babdb6'>
      <strong><%= book.name %></strong>
    </td>
  </tr>
  <% subjects = books[book].sort_by(&:created_at).sort_by(&:position) %>
  <% subjects.each do |subject| %>
    <tr>
      <td>
        <div class='actions'>
          <%= link_to _('Editar'), { controller: 'admin/subjects', action: 'edit', id: subject, _popup: true }, class: 'iframe_with_page_reload' %>
        </div>
      </td>
      <td><%= link_to subject.title, { controller: 'admin/subjects', action: 'edit', id: subject.id, _popup: true }, class: 'iframe_with_page_reload' %></td>
      <td><%= subject.department && subject.department.name %></td>
      <td>
        <div class='actions'>
          <%= link_to _('Remover'), { controller: 'admin/subjects', action: 'destroy', id: subject.id }, method: :delete, confirm: _('Tem certeza que quer remover?') %>
        </div>
      </td>
    </tr>
  <% end %>
<% end %>
</table>

<% unless @item.subjects.empty? %>
  <div style='margin-top: 1em'>
    <button class='iframe_with_page_reload' href='<%= url_for controller: 'admin/subjects', action: 'new', _popup: true, resource: { official_diary_id: @item.id } %>'><%= _('Adicionar assunto') %></button>
  </div>
<% end %>

app/views/admin/templates/_text_with_ckeditor.html.erb
<% content_for :javascripts do %>
  <script type="text/javascript">
    var CKEDITOR_BASEPATH = '/ckeditor/';
  </script>

  <%= javascript_include_tag '/ckeditor/ckeditor' %>
  <%= javascript_include_tag '/ckeditor/adapters/jquery' %>

  <script type="text/javascript">
    $(document).ready(function() {
      $(".rich_text").ckeditor();
      $('#tabs').tabs();
    });
  </script>
<% end %>

<%
  custom = { :rows => @resource.typus_options_for(:form_rows), :class => "rich_text" }
  options = options.merge!(custom)
%>

<% if @item.respond_to?(:add_files=) && @item.respond_to?(:extra_files) %>
  <div id="tabs">
    <ul>
    <li><a href="#tabs-1"><%= _('Conteúdo') %></a></li>
    <li><a href="#tabs-2"><%= _('Anexos') %></a></li>
    </ul>
    <div id="tabs-1">
      <%= form.text_area attribute, options %>
    </div>
    <div id="tabs-2">
      <table>
        <tr>
          <th><%= _('Título') %></th>
          <th><%= _('Arquivo') %></th>
          <th><%= _('Ações') %></th>
        </tr>
      <% @item.extra_files.order(:id).each do |extra_file| %>
        <tr>
          <td><%= extra_file.title %></td>
          <td><%= link_to extra_file.filename %></td>
          <td><%= link_to _('Remover'), '#', onclick: 'javascript:alert("Not yet"); return false' %></td>
        </tr>
      <% end %>
        <tr>
          <td colspan='3'>
            <button id='add-extra-file'>Adicionar anexo</button>
          </td>
        </tr>
      </table>

      <div id='template-title-tag' style='display: none'>
        <%= text_field_tag 'subject[add_files][][title]', '', placeholder: _("Título"), size: 30 %>
      </div>
      <div id='template-file-tag' style='display: none'>
        <%= file_field_tag 'subject[add_files][][upload]' %>
      </div>

    </div>
  </div>
<% else %>
  <li id="<%= attribute_id %>">
    <%= form.label attribute, label_text %>
    <%= form.text_area attribute, options %>
  </li>
<% end %>

app/views/admin/templates/_upload_image.html.erb
<li id="<%= attribute_id %>">
  <%= form.label attribute, label_text %>
  <table style='border: 1px solid #babdb6;'>
    <tr>
      <th>
        <%= _('Enviar um novo arquivo') %>
      </th>
      <th><%= _('Arquivo existente') %></th>
    </tr>
    <tr>
      <td>
        <ul>
          <li><%= _('Formato: JPG') %></li>
          <li><%= _('Dimensões: A4 (ex.: 2480x3508 ou 1240x1754 pixels)') %></li>
          <li><%= _('') %></li>
        </ul>
        <%= form.file_field attribute %>
      </td>
      <td>
        <%
          data_attr = attribute.to_s.sub(/_file$/, '')
          binary_data = @item.send(data_attr)
        %>
        <% if binary_data.present? %>
          <%= link_to _('Imagem JPG (%s)') % number_to_human_size(binary_data.size), action: data_attr, id: @item  %>
        <% else %>
          <em><%= _('(Nenhum)') %></em>
        <% end %>
      </td>
    </tr>
  </table>
</li>

app/views/admin/templates/_upload_pdf.html.erb
<% if params[:publish] %>

  <li id="<%= attribute_id %>">

  <p><strong><%= _('Instruções') %></strong></p>

  <p>
  <%= (_('1) Faça o <a href="%s" target="_blank">download</a> da versão atual do PDF') % download_path(@item.official_diary) + '?' + Time.now.to_i.to_s).html_safe %>
</p>

  <p>
  <%= _('2) Assine digitalmente o PDF') %>
  </p>

  <p>
  <%= _('3) Faça upload do PDF assinado no formulário abaixo') %>
  </p>

  <div>
    <table>
      <tr>
        <th><%= _('Upload do PDF assinado') %></th>
      </tr>
      <tr>
        <td>
          <%= form.file_field attribute %>
        </td>
      </tr>
    </table>
  </div>

  </li>

  <script type='text/javascript'>
    jQuery(function($) {
      $('h2').html("<%= _('Publicar Diário oficial') %>")
    });
  </script>
<% end %>