config/routes.rb
Urbo::Application.routes.draw do
  root :to => 'browse#index'
  match ':year/:month' => 'browse#month', :year => /\d+/, :month => /\d+/, :as => :period
  match ':year/:month/:day.:format' => 'browse#download', :year => /\d+/, :month => /\d+/, :day => /\d+/
  get "search", :controller => 'search', :action => 'index'

  delete 'logout' => 'sessions#destroy', :as => 'destroy_admin_session'
  get 'login' => 'sessions#new'
  resources :sessions

  resources :subscriptions
end

app/models/search.rb
class Search

  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :query

  def initialize(attrs=nil)
    attrs ||= {}
    attrs.each do |k,v|
      self.send("#{k}=", v)
    end
  end

  def results(page=nil)
    results = model.published.page(page)
    if !query.blank?
      results = results.search(query)
    end
    filters.each do |field|
      if !send(field.to_sym).blank?
        results = results.where(field => send(field.to_sym))
      end
    end
    preload.each do |association|
      results = results.preload(association)
    end
    results
  end

  def model
    Subject
  end

  attr_accessor :department_id, :book_id, :date, :number

  def filters
    [:department_id, :book_id, :date, :number]
  end

  def preload
    [:official_diary, :book, :department]
  end

  def blank?
    ([:query ] + filters).all? { |field| send(field).blank? }
  end

  def self.normalize(text)
    text.gsub(/(\d+)\.(\d+)/, '\1\2 \&').gsub(/\b0+(\d+)\b/, '\1 \&').gsub(/\b([\d\.]+)\/([\d\.]+)\b/, '\1 \2 \&')
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    @search = Search.new(params[:search])
    unless @search.date.blank?
      @search.date = Date.strptime(@search.date, I18n.translate('date.formats.default'))
    end
    unless @search.blank?
      @results = @search.results(params[:page])
    end
  end

end

app/helpers/search_helper.rb
module SearchHelper

  # FIXME this will be probably useful also in other contexts
  class BootstrapPaginationRenderer < WillPaginate::ActionView::LinkRenderer

    def html_container(html)
      tag(:ul, html, :class => 'pagination')
    end

    def page_number(page)
      classname = nil
      if (page == current_page)
        classname = 'active'
      end
      tag(:li, tag(:a, page, :href => url(page)), :class => classname)
    end

    def previous_or_next_page(page, text, classname)
      if page
        tag(:li, tag(:a, text, :href => url(page)), :class => classname)
      else
        tag(:li, tag(:a, text, :href => '#'), :class => classname + ' disabled')
      end
    end
  end

  def result_window(collection)
    from = collection.offset + 1
    to = collection.offset + collection.length
    total = collection.total_entries
    _('%d resultados encontrados (mostrando de %d a %d).') % [total, from, to]
  end

  def paginate(collection)
    will_paginate collection, :renderer => SearchHelper::BootstrapPaginationRenderer, :previous_label => '&laquo;', :next_label => ('&raquo;')
  end

end

app/views/search/_subject.html.erb
<table class='table table-condensed table-bordered'>
  <tr>
    <th><%= _('Assunto') %></th>
    <th><%= _('Caderno') %></th>
    <th><%= _('Órgão') %></th>
    <th><%= _('Edição') %></th>
    <th><%= _('Data') %></th>
    <td>
      <div class='hidden-xs'>
      <%= _('Baixar') %>
      <%= render partial: 'shared/pdf_format' %>
      </div>
    </td>
  </tr>
<% @results.each do |subject| %>
  <tr>
    <td><%= link_to subject.title, subject_download_path(subject) %></td>
    <td><%= subject.book.name %></td>
    <td><%= subject.department && subject.department.name || '—' %></td>
    <td><%= _('Edição %d, ano %d') % [subject.official_diary.number, subject.official_diary.year] %> </td>
    <td><%= l subject.official_diary.date %></td>
    <td><%= link_to content_tag('strong', _("Download do diário oficial")), subject_download_path(subject) , class: 'btn btn-success btn-sm', :target => '_blank' %></td>
  </tr>
<% end %>
</table>

app/views/search/index.html.erb
<% content_for :title, _('Pesquisar') %>

<div class='visible-xs visible-sm'>
  <% unless @search.blank? %>
    <% if @results.total_entries > 0 %>
      <div class='alert alert-success'>
        <%= result_window(@results) %>
        <%= link_to _('Visualizar'), '#results' %>
      </div>
    <% else %>
      <div class='alert alert-danger'>
        Nenhum resultado encontrado para os critérios selecionados.
      </div>
    <% end %>
  <% end %>
</div>

<form id='search-form' class='form-inline' role='form' action="<%= search_path %>">

  <div class='row'>
    <div class='form-group col-md-4'>
      <label for='search_query' class=''><%= _('Pesquisa') %></label>
      <%= text_field(:search, :query, id: 'search_query', class: "form-control", placeholder: _('Pesquisa')) %>
    </div>

    <div class='form-group col-md-2'>
      <label for='search_date' class=''><%= _('Data') %></label>
      <%= text_field :search, :date, value: !@search.date.blank? && l(@search.date) || '', class: 'datepicker form-control', id: 'search_date', placeholder: _('Data') %>
    </div>

    <div class='form-group col-md-2'>
      <label for='search_number' class=''><%= _('Edição') %></label>
      <%= text_field :search, :number, class: 'form-control', id: 'search_number', placeholder: _('Edição')  %>
    </div>
  </div>
  <div class='row'>
    <div class='form-group col-md-4'>
      <label for='search_department_id' class=''><%= _('Órgão') %></label>
      <%= select :search, :department_id, [[_('Qualquer órgão'), '']] + Department.all.map { |d| [d.name, d.id] }, {}, id: 'search_department_id', class: 'form-control' %>
    </div>

    <div class='col-md-2'>
      <label for='search_book_id' class=''><%= _('Caderno') %></label>
      <%= select :search, :book_id, [[_('Qualquer caderno'), '']] + Book.all.map { |b| [b.name, b.id] }, {}, id: 'search_book_id', class: 'form-control' %>
    </div>

    <div class='col-md-2'>
      <label>&nbsp;</label>
      <%= submit_tag _('Pesquisar'), class: "btn btn-default", style: 'display: block' %>
    </div>
  </div>

</form>

<% unless @search.blank? %>
  <% if @results.total_entries > 0 %>
    <div class='alert alert-success'>
      <%= result_window(@results) %>
    </div>
    <%= paginate @results %>
    <div id='results'>
      <%= render partial: 'subject' %>
    </div>
    <%= paginate @results %>
  <% else %>
    <div class='alert alert-danger'>
      Nenhum resultado encontrado para os critérios selecionados.
    </div>
  <% end %>
<% end %>