config/routes.rb
Urbo::Application.routes.draw do
  root :to => 'browse#index'
  match ':year/:month' => 'browse#month', :year => /\d+/, :month => /\d+/, :as => :period
  match ':year/:month/:day.:format' => 'browse#download', :year => /\d+/, :month => /\d+/, :day => /\d+/
  get "search", :controller => 'search', :action => 'index'

  delete 'logout' => 'sessions#destroy', :as => 'destroy_admin_session'
  get 'login' => 'sessions#new'
  resources :sessions

  resources :subscriptions
end

app/controllers/browse_controller.rb
# encoding: UTF-8

class BrowseController < ApplicationController

  include ApplicationHelper

  def index
    # this is a separate action *just* for a custom template
    month
  end

  def month
    @period = Period.new(params[:year], params[:month])
    @official_diaries = OfficialDiary.browse(@period)
  rescue ArgumentError => e
    not_found
  end

  def download
    year = Integer(params[:year])
    month = Integer(params[:month])
    day = Integer(params[:day])

    date = Date.new(year, month, day)
    official_diary = OfficialDiary.find_by_date(date)

    attachment = official_diary.attachment

    if attachment
      filename = official_diary_title(official_diary) + ".pdf"
      send_data attachment.data, type: 'application/pdf', filename: filename, disposition: 'inline'
      expires_in 1.day
    else
      not_found
    end
  end

  private

  def not_found
    render :text => ('Página não encontrada'), :status => :not_found
  end

end

app/helpers/browse_helper.rb
# encoding: UTF-8

module BrowseHelper

  # FIXME should use locale data instead!

  MONTHS = %w[Janeiro Fevereiro Março Abril Maio Junho Julho Agosto Setembro Outubro Novembro Dezembro]
  ABBREV = MONTHS.map { |m| m[0..2] }

  def period_title(period)
    _("%s de %d") % [MONTHS[period.month - 1], period.year]
  end

  def month_selector_data(period)
    (1..12).select do |month|
      Date.new(period.year, month, 1) <= Date.today
    end.map do |month|
      [ABBREV[month-1], month, month == period.month && :active || nil]
    end
  end

  def month_abbrev(n)
    ABBREV[n-1]
  end

  def subject_list(subjects)
    content_tag(:ul) do
      subjects.map { |s| content_tag :li, link_to(s.title, subject_download_path(s)) }.join.html_safe
    end
  end

end

app/views/browse/_table.html.erb
<table class='table table-condensed table-bordered'>
  <tr>
    <th><%= _('Edição') %></th>
    <th><%= _('Data') %></th>
    <th><%= _('Cadernos') %></th>
    <td class='hidden-xs'>
      <div>
      <%= _('Baixar') %>
      <%= render partial: 'shared/pdf_format' %>
    </div>
    </td>
  </tr>
  <% @official_diaries.each do |official_diary| %>
    <tr>
    <td><%= _('Edição %d, ano %d') % [official_diary.number, official_diary.year] %> </td>
    <td>
      <%= l official_diary.date %>

      <div class='visible-xs'>
        <%= link_to content_tag('strong', _("Download")), download_path(official_diary), class: 'btn btn-success btn-sm' %>
      </div>
    </td>
    <td>
      <ul>
        <% official_diary.subjects.group_by(&:book).each do |book,subjects| %>
          <li class='toc'>
          <%= link_to book.name, '#', 'data-toggle' => 'modal', 'data-target' => '#modal-%d-%d' % [official_diary.id, book.id] %>

          </button>
          <!-- Modal -->
          <div class="modal fade" id="modal-<%= official_diary.id %>-<%= book.id%>" tabindex="-1" role="dialog" aria-labelledby="modal-label-<%= official_diary.id %>-<%= book.id %>" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                  <h4 class="modal-title" id="modal-label-<%= official_diary.id %>-<%= book.id %>"><%= book.name %></h4>
                </div>
                <div class="modal-body">
                  <h5><%= ["Edição #{official_diary.number}, #{l official_diary.date, :format => :long}"].join(' — ') %></h5>
                  <%= subject_list(subjects) %>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal"><%= _('Fechar') %></button>
                </div>
              </div>
            </div>
          </div>



          </li>
      <% end %>
      </ul>
    </td>
    <td class='hidden-xs'>
      <%= link_to content_tag('strong', _("Download do diário oficial")), download_path(official_diary), class: 'btn btn-success btn-sm', :target => '_blank' %>
    </td>
  </tr>
<% end %>
</table>

app/views/browse/index.html.erb
<% content_for :banner do %>
<div class='banner hidden-xs'>
</div>
<% end %>
<%= render file: 'browse/month' %>

app/views/browse/month.html.erb
<% content_for :title, period_title(@period) %>
<% content_for :header do %>
  <div class='hidden-xs'>

    <div class='btn-group'>
      <a class='btn btn-default dropdown-toggle active' data-toggle='dropdown' href='#'>
        <%= @period.year %>&nbsp;<span class="caret"></span>
      </a>
      &nbsp;
      <ul class='dropdown-menu'>
        <% OfficialDiary.all_years.each do |year| %>
          <li><%= link_to year, period_path(year, @period.month) %></li>
        <% end %>
      </ul>
    </div>

    <div class='btn-group'>
      <% month_selector_data(@period).each do |entry| %>
        <%= link_to entry[0], period_path(@period.year, entry[1]), :class => "btn btn-default #{entry[2]}" %>
      <% end %>
    </div>

    <%= link_to subscriptions_path, class: 'btn btn-info', title: _('Inscreva-se para receber notificações por email quando uma nova edição do diário oficial é publicada') do %>
      <span class="glyphicon glyphicon-envelope"></span>
      <%= _('Assinar') %>
    <% end %>

  </div>

  <div class='visible-xs'>
    <div class='btn-group'>
      <a class='btn btn-default dropdown-toggle active' data-toggle='dropdown' href='#'>
        <%= @period.year %>&nbsp;<span class="caret"></span>
      </a>
      &nbsp;
      <ul class='dropdown-menu'>
        <% OfficialDiary.all_years.each do |year| %>
          <li><%= link_to year, period_path(year, @period.month) %></li>
        <% end %>
      </ul>
    </div>

    <div class='btn-group'>
      <a class='btn btn-default dropdown-toggle active' data-toggle='dropdown' href='#'>
        <%= month_abbrev(@period.month) %>&nbsp;<span class="caret"></span>
      </a>
      &nbsp;
      <ul class='dropdown-menu'>
        <% month_selector_data(@period).each do |entry| %>
          <li><%= link_to entry[0], period_path(@period.year, entry[1]) %></li>
        <% end %>
      </ul>
    </div>

    <%= link_to subscriptions_path, class: 'btn btn-info', title: _('Inscreva-se para receber notificações por email quando uma nova edição do diário oficial é publicada') do %>
      <span class="glyphicon glyphicon-plus"></span>
      <%= _('email') %>
    <% end %>

  </div>
<% end %>

<%= render partial: 'browse/table' %>